# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "JBerczel's"
tagline:          "Notes on learning Web Development"
description:      "Thoughts and notes on learning Web Development"
url:              http://jberczel.github.com/blog

author:
  name:           'Jamie Berczel'
  url:            https://twitter.com/Jberczel

paginate:         5
paginate_path:    "/blog/page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Jberczel/jberczel.github.io

plugins: [jekyll-paginate]
